// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARO-eMpq0ejRGfSC5AveSdvEwxSbE287M',
    appId: '1:420072047920:web:89a30d073301c9342474f5',
    messagingSenderId: '420072047920',
    projectId: 'todoo-ae2dc',
    authDomain: 'todoo-ae2dc.firebaseapp.com',
    storageBucket: 'todoo-ae2dc.appspot.com',
    measurementId: 'G-1PNLCSN9GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyM1kl3WVPwN0Ixyjc8nFhfXTbfv-hzLw',
    appId: '1:420072047920:android:903af98a312373742474f5',
    messagingSenderId: '420072047920',
    projectId: 'todoo-ae2dc',
    storageBucket: 'todoo-ae2dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJDZUxdarHY9IHFWGvzdyqmRhSzAJEmk8',
    appId: '1:420072047920:ios:4292db8faef0c11b2474f5',
    messagingSenderId: '420072047920',
    projectId: 'todoo-ae2dc',
    storageBucket: 'todoo-ae2dc.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJDZUxdarHY9IHFWGvzdyqmRhSzAJEmk8',
    appId: '1:420072047920:ios:12ff4037a43744182474f5',
    messagingSenderId: '420072047920',
    projectId: 'todoo-ae2dc',
    storageBucket: 'todoo-ae2dc.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}
